# Makefile for skip_list

CC = gcc
CFLAGS = -Wall -Wextra
OUTDIR = out
TARGET = $(OUTDIR)/skip_list

all: $(OUTDIR) $(TARGET)

$(OUTDIR):
	mkdir -p $(OUTDIR)

$(TARGET): skip_list.c
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm -f $(TARGET)

.PHONY: all clean
