# Makefile for 2_linked_lists

CC = gcc
CFLAGS = -Wall -Wextra
OUTDIR = out
TARGET = $(OUTDIR)/2_linked_lists

all: $(OUTDIR) $(TARGET)

$(OUTDIR):
	mkdir -p $(OUTDIR)

$(TARGET): 2_linked_lists.c
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm -f $(TARGET)

.PHONY: all clean
